[package]
name = "real-app"
version = "0.1.0"
authors = ["imrany <imranmat254@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-web = "1.0.8"
argon2 = "0.5.0"
cargo-watch = "8.4.0"
chrono = "0.4.24"
dotenv = "0.15.0"
env_logger = "0.10.0"
jsonwebtoken = "8.3.0"
rand_core = "0.6.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.94"
sqlx = "0.6.3"
sqlx-cli = "0.6.3"
openssl = { version = "0.10", features = ["vendored"] }
